### ISSUE TITLE
Release 1.6.2

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#371]
I suppose it worth to release a new bugfix release 1.6.2 with some tiny code imports from 1.7.0.

TODO list with PRs:
---
Beta1:
- [x] Fix #17 - 6eb21fe
- [x] Update leap seconds - #398
- [x] Import patches from GNU/Linux & *BSD distributions - #396
- [x] Update to Lua5.3 - #394, #419
- [x] Make Kpc translatable - #418 
- [x] Make GTK+ frontend translatable - #423
- [x] Fix OSX frontend for modern OSX requirements - #390, #397,#400, #402, #403, #404, #409 
- [x] Fix all `-Wall` warnings - #399
- [x] Win32: load celestia.cfg from $HOME - #428 
- [x] Win32: use $APPDIR as storage for written files - #428 
- [ ] Win32: update dependencies (optional, vcpkg can be used instead) -
- [x] Win32: update MSVC project file for MSVC2015 - #424
- [x] Win32: update innosetup configuration - #430
- [x] Win32: backport ff2455857 - #420
- [x] Update po/translate_resources.pl to create AMD64 DLL's - #430
---
Beta2:
- [x] Update translations - 
- [x] Update INSTALL.txt to mention autoreconf -
- [x] Support LuaJit - 
- [x] Win: Provide libspice.dll
- [ ] Win: Make "Disable display scaling on high DPI setting" unneeded or workaround it - 
- [x] Win: Increase "Render -> Select display mode" hsize - 
- [x] Win: fix bundled gettext
- [x] Mac: Read data from 1.6.1 if there is previous installation - #433 
- [x] Mac: Migrate to ARC - #412
- [x] Mac: Better support for dark mode - #439 
- [x] Mac: Additional localization - #440 
- [x] Mac: Provide icons of all resolutions
- [x] Win: Fix star browser bug - #618 
- [x] Fix scripted orbits and rotations - #578

**Comment by eyvallah** [comment]
on all platforms? I feel it will be quite some effort to make the 1.6.1 branch work.

**Comment by 375gnu** [comment]
It would be good to have it for all platforms, but it depends on the
efforts required actually

**Comment by eyvallah** [comment]
> It would be good to have it for all platforms, but it depends on the efforts required actually

I just tried building the 1.6.1 branch with the Xcode project, to my surprise, it wasn't difficult to get it running.  the only thing that required some work will be the replacement for SetThemeCursor.

**Comment by 375gnu** [comment]
sounds good

**Comment by 375gnu** [comment]
@pirogronian what do you think?

**Comment by pirogronian** [comment]
I bless this idea.

**Comment by eyvallah** [comment]
there are a few platform issues related to Mac, since it has changed over the years

1. 64 bit, the coming macOS release this September is going to drop 32bit support entirely, and 1.6.1 will not run on macOS 10.15 anymore. thus 1.6.2 is urgently needed
2. Codesigning, a non-codesigned app refuses to run on the current releases of macOS. Codesigning prevents its bundle from being modified, thus user couldn't modify the "CelestiaResources" data folder in the bundle themselves.
3. Sandbox, Apple encourages developer to sandbox its app. A sandboxed app can't read arbitrary files unless through file open panel/drag and drop, etc. A non-sandboxed app can't be distributed on the App Store.

**Comment by 375gnu** [comment]
@eyvallah could you handle p2&3? If not, we can still distribute Celestia through homebrew, but in that case only experienced users will be able to use it.

**Comment by eyvallah** [comment]
@375gnu I will fix these as I already have done in my personal swift Celestia project which i might contribute as a base native setup for 1.7.0 sometime. Also I  have Apple developer ID so i can codesign Celestia and host it on the app store, and hopefully it will bring this project much more exposure. To provide flexibility of data folder/config file path, i think i'll need to add some button, input controls in the setting dialog to allow user to specify which folder to use for the data/which file as the config file other than the one that's bundled(env variables, launch arguments won't work because the sandbox disallows reading arbitrary files).

**Comment by 375gnu** [comment]
> I will fix these as I already have done in my personal swift Celestia project which i might contribute as a base native setup for 1.7.0 sometime.

Are you Markerz from the forum?

**Comment by eyvallah** [comment]
ye ah that's me

**Comment by 375gnu** [comment]
Hi @eyvallah I've just created a 1.6.2-beta1 tag. Could you provide an OS X build for it so OS Xusers can join testing?

**Comment by eyvallah** [comment]
I’ll see to it tomorrow

**Comment by pirogronian** [comment]
It looks like installation framework is incomplete. Instruction talks about `configure` script, which is missing. CMake also is missing. Just `make && makeinstall`? How to provide interface and/or prefix path?

**Comment by munix9** [comment]
@pirogronian `autoreconf -fi`
@375gnu do you need 1.6.2~beta1 packages for Debian 10/Ubuntu 18.04 on OBS?

**Comment by 375gnu** [comment]
@munix9 no, for GNU/Linux side most changes are tested already, so no need to waste time building them

**Comment by pirogronian** [comment]
@munix9 Thanks. But it would be good to mention it in installation instruction.

**Comment by eyvallah** [comment]
@375gnu minor fixes are applied for the Mac build, see #432 . also the binary is put in the release section.

**Comment by 375gnu** [comment]
@dlshcbmuipmam do you know how to enable  "Disable display scaling on high DPI setting"  option to to make native win UI compatible with high DPI?

**Comment by eyvallah** [comment]
high resolution icons are needed for macOS distribution, I wonder if we will just use the icon in the master branch for 1.6.2 also? @375gnu 

current macOS icon is
![celestia128x128](https://user-images.githubusercontent.com/17924287/66664672-894c6e00-ec7f-11e9-98d1-cc9167f79713.png)

**Comment by 375gnu** [comment]
> I wonder if we will just use the icon in the master branch for 1.6.2 also?

I'm in favor of this.

**Comment by SevenSpheres** [comment]
- [ ] [Fix star browser bug](https://celestia.space/forum/viewtopic.php?p=147576#p147576)

**Comment by SevenSpheres** [comment]
How close is a final 1.6.2 release? Any guess?

**Comment by 375gnu** [comment]
This still has to be fixed: "Win: Fix star browser bug". I don't see why it emerge. In 1.7 it doesn't exist.

**Comment by SevenSpheres** [comment]
> This still has to be fixed: "Win: Fix star browser bug". I don't see why it emerge. In 1.7 it doesn't exist.

This may or may not be helpful, but Alexell's version of 1.7 [had the same bug](https://celestia.space/forum/viewtopic.php?f=4&t=17731&start=20).

**Comment by 375gnu** [comment]
very interesting, basically winstarbrowser.cpp is the same, changes are negilible

**Comment by 375gnu** [comment]
crappy m$. their compiler generates incorrect code.

**Comment by 375gnu** [comment]
@eyvallah regarding "Mac: Provide icons of all resolutions" - will you do this? or can we skip this?

**Comment by eyvallah** [comment]
> @eyvallah regarding "Mac: Provide icons of all resolutions" - will you do this? or can we skip this?

it is already done, I forgot to tick that 😂

**Comment by 375gnu** [comment]
@eyvallah could you build from `1.6.2-beta2` tag and upload it to the releases?

**Comment by SevenSpheres** [comment]
Some small fixes that need to be made for the final release:
- update year in README and "About Celestia" window - it should say "2001-2020"
- update URLs in README (shatters.net -> celestia.space; SourceForge -> GitHub)
- add any more updates to ChangeLog
- either make similar updates to CelestiaGuide.html, or have "User Guide" point to Wikibooks as in 1.7.0

**Comment by eyvallah** [comment]
@375gnu done, next time please let me know in advance so i can bump the build number before making a release

**Comment by SevenSpheres** [comment]
Hi @375gnu, I was trying to push changes to the 1.6.x branch on my fork but instead pushed them to the main CelestiaProject branch. I am unable to revert this, I get this error:
```
$ git push origin 1.6.x --force
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/1.6.x.
remote: error: Cannot force-push to this protected branch
To https://github.com/CelestiaProject/Celestia.git
 ! [remote rejected]   1.6.x -> 1.6.x (protected branch hook declined)
error: failed to push some refs to 'https://github.com/CelestiaProject/Celestia.git'
```
Please help!

**Comment by SevenSpheres** [comment]
I still don't know why my commit went to the CelestiaProject branch instead of my branch, but since @375gnu said on Discord that he approves, I guess there's no need to revert it. Things that still need to be done:
- update ChangeLog
- update "INSTALLING IN UNIX AND LINUX"
- either update CelestiaGuide.html, or have "User Guide" point to Wikibooks as in 1.7.0
- anything else?

**Comment by SevenSpheres** [comment]
Any idea when the remaining checklist items will be completed, and when/if #673 will be fixed?

**Comment by 375gnu** [comment]
No idea at all. Especially taking into account that now I only occasionally have access to my PC where I can msvc.

**Comment by 375gnu** [comment]
By the way, you can fix this point:
> either make similar updates to CelestiaGuide.html,

**Comment by SevenSpheres** [comment]
> By the way, you can fix this point:

What specifically should I fix there?

**Comment by 375gnu** [comment]
Update URLs for example.

**Comment by SevenSpheres** [comment]
> Update URLs for example.

Oh I was thinking you meant I should fix the wording of the point itself, for some reason.

**Comment by Baltix** [comment]
I've added debian packaging stuff (/debian folder with needed files inside) based on Celestia 1.6.1 official packages from Debian/Ubuntu and created automated deb packages building recipe for all supported Ubuntu releases, see
https://salsa.debian.org/baltix-team/packages4debian/celestia-1.6.x
https://code.launchpad.net/~baltix/+recipe/celestia-1.6.x
(Install latest Celestia 1.6.2 packages with these commands: sudo add-apt-repository ppa:baltix/ppa && sudo apt install celestia)

I sugggest you to copy /debian folder from https://salsa.debian.org/baltix-team/packages4debian/celestia-1.6.x.git to 1.6.x branch

Btw, it seems we should deprecate --with-gnome build option - libgnomeui and other GNOME2 libraries are unmaintained since 2015 and were removed from Debian and Ubuntu in 2019, see https://launchpad.net/ubuntu/+source/libgnomeui/+bug/1825972
Please add this info at least to INSTALL file.

**Comment by 375gnu** [comment]
@Baltix thank you for sharing information about ppa. Regarding `--with-gnome`, we will remove it from `INSTALL`.
