### ISSUE TITLE
Fixed pipeline removal

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#501]
- [x] Remove GL1.x renderers
- [x] Star field as scaled disks / fuzzy points
- [x] Star field as points - #535
- [x] Planet rings - #271
- [x] Renderer::renderMarker - #308
- [x] Globular clusters - #312 
- [x] Terminator - #314
- [x] Renderer::renderSelectionPointer, ecliptic line - #497 
- [x] Renderer::renderObject - #499
- [x] SkyGrid - #532
- [x] Galaxy - #529
- [x] Renderer::renderObjectAsPoint - #533
- [x] Renderer::renderCometTail - #505
- [x] Use vertex buffer in CurvePlot - #311
- [x] Add shaders for CurvePlot - #505
- [x] Planetographic Grid - #530
- [x] CelTXF
- [x] Renderer::renderParticles (currently unused) - #505
- [ ] Renderer::renderToBlurTexture (hidden behind `#if USE_HDR`)

**Comment by eyvallah** [comment]
will we see gles support soon after this list is done?

 I tried to compile for iOS, although GLEW is not available on iOS, but it was interesting to see what code throws error when compiling for iOS, it's an amazingly short list

glu function
gluOrtho2D
gluBuild2DMipmaps
gluPerspective
gluProject
gluLookAt

wordexp, wordfree is not available on iOS, well you don't really have a home directory on iOS, it's useless anyway

fixed pipeline functions passes compilation since I think, GLEW wrapped them

**Comment by 375gnu** [comment]
yeah, glu is not available for ES and modern GL. gluBuild2DMipmaps can be easily replaced with glGenerateMipmap. Other functions are more complicated to replace. ES is more like core profile of modern desktop GL, it doesn't support matrix functions so they should be replaced with glm or our own alternatives. We already have LookAt in master, and I have Ortho2D in one of my wip branches.
